# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    sources:
      - $package$
      - lib/**
      - test/**
      - pubspec.yaml
    builders:
      pubspec_generator:
        options:
          output: lib/src/model/pubspec.yaml.g.dart