name: flutter_in_store_app_version_checker

description: >
  A lightweight flutter plugin to check if your app is up-to-date on GooglePlay or AppStore.

version: 1.6.0

homepage: https://github.com/ziqq/flutter_in_store_app_version_checker

repository: https://github.com/ziqq/flutter_in_store_app_version_checker

issue_tracker: https://github.com/ziqq/flutter_in_store_app_version_checker/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.2
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  mockito: ^5.4.3

  flutter_lint_rules:
    git:
      url: https://github.com/ziqq/flutter_lint_rules.git
      ref: main

flutter:
  plugin:
    platforms:
      android:
        package: com.example.in_store_app_version_checker
        pluginClass: InStoreAppVersionCheckerPlugin
      ios:
        pluginClass: InStoreAppVersionCheckerPlugin
