name: flutter_in_store_app_version_checker

description: >
  A lightweight flutter plugin to check if your app is up-to-date on GooglePlay or AppStore.

version: 1.7.0

publish_to: 'https://pub.dartlang.org'

homepage: https://github.com/ziqq/flutter_in_store_app_version_checker

repository: https://github.com/ziqq/flutter_in_store_app_version_checker

issue_tracker: https://github.com/ziqq/flutter_in_store_app_version_checker/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Annotations
  meta: ^1.9.1

  # Http
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Utilities
  collection: any
  path: any

  build_runner: ^2.4.11
  pubspec_generator: ^4.0.0

  # Testing
  mockito: ^5.4.4

  # Linting
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.in_store_app_version_checker
        pluginClass: InStoreAppVersionCheckerPlugin
      ios:
        pluginClass: InStoreAppVersionCheckerPlugin
