name: flutter_in_store_app_version_checker

description: >
  "A lightweight flutter plugin to check if your app is up-to-date on GooglePlay or AppStore. Made with ❤️ by ziqq."

version: 1.10.0

homepage: https://github.com/ziqq/flutter_in_store_app_version_checker

repository: https://github.com/ziqq/flutter_in_store_app_version_checker

issue_tracker: https://github.com/ziqq/flutter_in_store_app_version_checker/issues

funding:
  - https://www.buymeacoffee.com/ziqq
  - https://www.patreon.com/ziqq
  - https://boosty.to/ziqq

platforms:
  android:
  ios:

#screenshots:
#  - description: 'Example of using the library to check app version.'
#    path: example.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Annotations
  meta: ^1.16.0

  # Http
  http: ^1.3.0

  # Utilities
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15

  # Testing
  mockito: ^5.4.6

  # Linting
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.instoreappversionchecker
        pluginClass: InStoreAppVersionCheckerPlugin
      ios:
        pluginClass: InStoreAppVersionCheckerPlugin
