name: example_gradle_8

description: Demonstrates how to use the flutter_in_store_app_version_checker

version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any

  flutter_in_store_app_version_checker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
